### ISSUE TITLE
How can I apply both SQL and hook on users here:

### ISSUE THREAD

**Issue by jasir** [marpple/MQL#1]
```
result = await ASSOCIATE`
    users ${{ hook: userAdd, column: COLUMN('login') }} ${SQL`where id = ${userId}`} 
      < issues ${{
        column: COLUMN('subject'),
        left_key: 'id',
        key: 'author_id',
        row_number: [1, SQL`id desc`],
        hook: issueAdd
      }}
        - trackers ${{ column: COLUMN('name') }}
```

where_id is not applied. When I swap hook and column with SQL, then where is applied, but not column and hook...

**Comment by nfreedom9** [comment]
result = await ASSOCIATE`
    users ${{ hook: userAdd, column: COLUMN('login'), query: SQL`where id = ${userId}` }} 
      < issues ${{
        column: COLUMN('subject'),
        left_key: 'id',
        key: 'author_id',
        row_number: [1, SQL`id desc`],
        hook: issueAdd
      }}
        - trackers ${{ column: COLUMN('name') }}

**Comment by jasir** [comment]
Wow, thank you very much for very fast response! It works!

I think that `query` key of configuration object should be mentioned in documentation!

Great work!

**Comment by jasir** [comment]
Thanks again for this great library, closing issue...
